# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b019fc783f44dfec1401893e006243ff30ebf9a3be8aabd7565a0b589831d2d415a90114690c9228f8ee1e41a29bc43d168f80f624b0373834f79dfab37d8fc

test:
  secret_key_base: 38bc772a7248221f50d1bfe0ad768eb03bb599945a3661c35bd583976628bcae3c04bff82c24811e35fee3961b04412898cfa57318b4f8c430dac9ee6b75dcc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
